dump_dir: /mnt/jfzn/lzh/modelbase/gla-7B-freelong-batch8-16k
name: gla-hybrid-7B-freelong-chunk8k-16k

steps: 5
varlen: false
seed: 42
grad_acc_steps: 4
optim:
  scheduler: cosine
  lr: 1e-5
  weight_decay: 0.0
  warmup: 200
  lr_min_ratio: 0.001
  clip: 1.0
distributed:
  fsdp_type: full_shard
  compile: false
  model_dtype: bf16
  matmul_allow_tf32: false
  activation_checkpointing: false
  tp_size: 1
  dp_replicate: 1
  dp_shard: 8
  sp_size: 1
model:
  name_type: backbone
  model_name: "gla"
  config_path: "/mnt/jfzn/lzh/modelbase/gla-7B-hybrid"
  # pt_path: "/mnt/jfzn/lzh/modelbase/Qwen3-8B-Base"
  seed: 42
  dim: 2048
  n_layers: 32
  meta_init: true
  # n_heads: 32
  vocab_size: 32000
  # memory_efficient_checkpointing: False
  # chunk_size: null
  # rope_theta: 1_000_000
  # ffn_dim_multiplier: 3.0
  # multiple_of: 256

data:
  sources:
    load_from_disk./mnt/jfzn/lzh/database/slim_test_hfds: 100.0
  batch_size: 1
  prefetch_size: 32
  # seq_len: 8192
  # seq_len: 10240
  seq_len: 16384
  # seq_len: 32768
  # seq_len: 65536
  # seq_len: 524288
  # seq_len: 1048576  # 1M
  n_views: 1
  load_async: true
  add_bos: False
  add_eos: False
  pad_token_id: 0
  tokenizer:
    name: gla
    path: /mnt/jfzn/lzh/modelbase/gla-7B
checkpoint:
  # init_ckpt_path: /mnt/jfzn/lzh/modelbase/gla-1B-dcp # must be a dcp model
  dump:
    every: 1_000
    keep: 4
logging:
  freq: 1
  wandb:
    dir: ./wandb_log
    entity: XLM
    project: freelong-fsdp
    group: gla-7b-mem-fuselinearCE